- name: add variables
  include_vars: 
    dir: vars

- name: Get datestamp from the system
  shell: date +"%Y%m%d"
  register: dstamp

- name: Set current date stamp variable
  set_fact:
    cur_date: "{{ dstamp.stdout }}"

# Host Setup
- name: Set static hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: install packages
  apt:
    name:net-tools
  state: present

 
- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'

- name: Disable tunneled clear-text passwords
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication yes'
    line: 'PasswordAuthentication no'

- name: Copy filebeat over to server
  copy:
    src: files/filebeat-8.14.3-amd64.deb
    dest: /home/{{user}}
    owner: "{{user}}"
    group: "{{user}}"

- name: install filebeat
  shell: |
    cd /home/{{user}}
    sudo apt install ./filebeat-8.14.3-amd64.deb -y

- name: enable filebeat
  systemd: 
    name: filebeat
    state: started
    enabled: true